# Generated by Django 3.1.1 on 2020-09-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_product',
            name='order_fk',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.DeleteModel(
            name='vendor_product',
        ),
        migrations.DeleteModel(
            name='company_product',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
