# Generated by Django 3.1.1 on 2020-09-20 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20200919_1316'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_product_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company_product',
            name='order_fk',
        ),
        migrations.AddField(
            model_name='company_product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='vendor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login_signup.vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login_signup.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.company_product'),
        ),
        migrations.AddField(
            model_name='vendor_product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_product',
            name='vendor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.vendor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor_product',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='vendor_product',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vendor_product_categories'),
        ),
    ]
