# Generated by Django 3.1.1 on 2020-09-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200920_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_product',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
