# Generated by Django 3.1.1 on 2020-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200920_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
