# Generated by Django 3.1.1 on 2020-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_order_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_product',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(null=True),
        ),
    ]
