# Generated by Django 3.1.1 on 2020-09-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20200919_1316'),
        ('products', '0006_auto_20200920_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='prediction_msg',
        ),
        migrations.AddField(
            model_name='notification',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Demand', 'Possible Rise in Demand Soon'), ('Bid Success', 'Your Bid Has Been Accepted by Company A'), ('Relevant Bid', 'Company A Has Posted A Requirement which might Interest you')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor_product',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor_product_categories',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='noti_msg',
            field=models.CharField(max_length=1000),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='vendor_fk',
        ),
        migrations.AddField(
            model_name='notification',
            name='vendor_fk',
            field=models.ManyToManyField(blank=True, to='login_signup.Vendor'),
        ),
        migrations.CreateModel(
            name='raw_material_requirments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=50)),
                ('issue_date', models.DateField(null=True)),
                ('bids', models.ManyToManyField(blank=True, related_name='bids', to='login_signup.Vendor')),
                ('category_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vendor_product_categories')),
                ('vendor_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login_signup.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='bid_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.CharField(max_length=1000)),
                ('req_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.raw_material_requirments')),
                ('vendor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_signup.vendor')),
            ],
        ),
    ]
