# Generated by Django 3.1.1 on 2020-09-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20200919_1316'),
        ('products', '0007_auto_20200921_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_msg', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('New Bid', 'New Bid'), ('New Order', 'New Order')], max_length=200, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('customer_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login_signup.customer')),
                ('vendor_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login_signup.vendor')),
            ],
        ),
    ]
