# Generated by Django 3.1.1 on 2020-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_company_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Future Demand', 'Possible Rise in Demand Soon'), ('Bid Success', 'Your Bid Has Been Accepted by Company A'), ('Relevant Bid', 'Company A Has Posted A Requirement which might Interest you')], max_length=200, null=True),
        ),
    ]
