# Generated by Django 3.1.1 on 2020-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200921_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_product',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
